[project]
name = "clipik"
version = "0.1.4"
description = "Synchronize clipboard buffer by network"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=4.0.0",
    "loguru>=0.7.3",
    "pydantic>=2.13.5",
    "typing>=3.10.0.0",
    "websockets>=17.1",
    "zeroconf>=0.151.3",
]
license = "Unlicense"

[project.scripts]
clipik = "clipik:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "basedpyright>=1.40.0",
    "twine>=7.0.0",
]

[project.urls]
Homepage = "https://gitflic.ru/project/kurilka/clipik"
Github = "https://github.com/TheWhatis/clipik"
